name: Container

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
    branches:
      - "master"

jobs:
  # build docker images in Git context
  # https://github.com/marketplace/actions/build-and-push-docker-images#git-context
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.3.0
      - name: Login to Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.DCR_HOST }}
          username: ${{ secrets.DCR_USERNAME }}
          password: ${{ secrets.DCR_TOKEN }}
      - name: Get version of branch
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2.4.0
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DCR_HOST }}/${{ secrets.DCR_REPOSITORY }}/isthejiradown:latest
            ${{ secrets.DCR_HOST }}/${{ secrets.DCR_REPOSITORY }}/isthejiradown:${{ steps.get_version.outputs.VERSION }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
