name: PHP Lint

on:
  pull_request:
  push:
    branches:
      - "master"

jobs:
  phplint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: michaelw90/PHP-Lint@master
